# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2016, 4, 26, 13, 1, 31, 698360))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdcontacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
