# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 4, 26, 13, 20, 13, 938121)),
        ),
    ]
