# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20160426_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 26, 13, 39, 15, 530772, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
