# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 14:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20160426_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 4, 27, 14, 42, 32, 296819, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.TextField(default=datetime.datetime(2016, 4, 27, 14, 42, 37, 572562, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
